version: "3.8"

services:
  fastapi-app:
    #image: zeno-data-analytics
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Maps port 8000 on the host to port 8000 in the container
      - "8787:8787"  # Maps port 8787 on the host to port 8787 in the container for Dask dashboard
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ANALYSES_TABLE_NAME=Analyses-dev
      - ANALYSIS_RESULTS_BUCKET_NAME=gnw-analytics-api-analysis-results-dev
      - API_KEY=${API_KEY}
      - PYTHON_VERSION=3.13  
      - PYTHONPATH=/app
    volumes:
      - $HOME/.aws:/home/appuser/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
