# Run tests in specified project directory
on:
  workflow_call:
    inputs:
      image_type:
        type: string
        description: 'Type of image to build. E.g. "branch" or "release"'
        required: true
      project_dir:
        required: true
        type: string
      run_platform:
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      AWS_ZENO_ACCOUNT_ID:
        required: true
      AWS_ZENO_ACCESS_KEY_ID:
        required: true
      AWS_ZENO_SECRET_ACCESS_KEY:
        required: true
      GFW_API_KEY:
        required: true
      DASK_SCHEDULER_ADDRESS:
        required: true
      AWS_ACCESS_KEY_ID_FOR_TESTS:
        required: true
      AWS_SECRET_ACCESS_KEY_FOR_TESTS:
        required: true

env:
  CONTAINER_REGISTRY: ${{ secrets.AWS_ZENO_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  CONTAINER_REPO_NAME: gnw-analytics-${{ inputs.project_dir }}


jobs:
  run_tests:
    runs-on: ${{ inputs.run_platform }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ inputs.image_type }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ZENO_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ZENO_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI if running under ACT
        if: ${{ env.ACT }}
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          /tmp/aws/install --update
          rm -rf /tmp/aws/

      - name: Login to container registry
        if: success()
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ env.CONTAINER_REGISTRY }}

      - name: Explicitly pull image
        if: success()
        run: |
          docker pull ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPO_NAME }}:${{ env.IMAGE_TAG }}

      - name: Run tests
        if: success()
        run: |
          docker run --rm \
            -e API_KEY=${{ secrets.GFW_API_KEY }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_FOR_TESTS }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_FOR_TESTS }} \
            -e ANALYSES_TABLE_NAME=Analyses-test \
            -e ANALYSIS_RESULTS_BUCKET_NAME=gnw-analytics-api-analysis-results-test \
            ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPO_NAME }}:${{ env.IMAGE_TAG }} \
            sh -c "uv sync --locked --no-install-project --dev -p 3.13.5 && pytest test --disable-warnings"
